spring.application.name=ApiGateway
server.port=8080

eureka.client.service-url.defaultZone=http://${DISCOVERY_SERVER:localhost}:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${random.value}

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.password=${REDIS_PASS}
spring.data.redis.port=6379

spring.cloud.loadbalancer.cache.ttl=5s
spring.cloud.loadbalancer.cache.capacity=256
spring.cloud.loadbalancer.eager-load.clients=AuthService,UserService,BookBorrowService
eureka.client.registry-fetch-interval-seconds=5

#auth-service
spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://AuthService
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/auth/**
spring.cloud.gateway.server.webflux.routes[0].predicates[1]=Method=POST

spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=3
spring.cloud.gateway.server.webflux.routes[0].filters[1].name=RequestRateLimiter
spring.cloud.gateway.server.webflux.routes[0].filters[1].args.key-resolver=#{@ipResolver}
spring.cloud.gateway.server.webflux.routes[0].filters[1].args.redis-rate-limiter.replenish-rate=2
spring.cloud.gateway.server.webflux.routes[0].filters[1].args.redis-rate-limiter.burst-capacity=10
spring.cloud.gateway.server.webflux.routes[0].filters[1].args.deny-empty-key=false
spring.cloud.gateway.server.webflux.routes[0].filters[1].args.status-code=TOO_MANY_REQUESTS

spring.cloud.gateway.server.webflux.routes[0].filters[2].name=CircuitBreaker
spring.cloud.gateway.server.webflux.routes[0].filters[2].args.name=authCircuit
spring.cloud.gateway.server.webflux.routes[0].filters[2].args.fallbackUri=forward:/fallback
spring.cloud.gateway.server.webflux.routes[0].filters[2].args.statusCodes=500,503
resilience4j.circuitbreaker.instances.authCircuit.failureRateThreshold=50
resilience4j.circuitbreaker.instances.authCircuit.slidingWindowSize=20
resilience4j.circuitbreaker.instances.authCircuit.minimumNumberOfCalls=10
resilience4j.circuitbreaker.instances.authCircuit.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.authCircuit.permittedNumberOfCallsInHalfOpenState=5
resilience4j.circuitbreaker.instances.authCircuit.automaticTransitionFromOpenToHalfOpenEnabled=false

#user-service
spring.cloud.gateway.server.webflux.routes[1].id=user-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://UserService
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/user/**

spring.cloud.gateway.server.webflux.routes[1].filters[0]=StripPrefix=3
spring.cloud.gateway.server.webflux.routes[1].filters[1].name=RequestRateLimiter
spring.cloud.gateway.server.webflux.routes[1].filters[1].args.key-resolver=#{@ipResolver}
spring.cloud.gateway.server.webflux.routes[1].filters[1].args.redis-rate-limiter.replenish-rate=2
spring.cloud.gateway.server.webflux.routes[1].filters[1].args.redis-rate-limiter.burst-capacity=10
spring.cloud.gateway.server.webflux.routes[1].filters[1].args.deny-empty-key=false
spring.cloud.gateway.server.webflux.routes[1].filters[1].args.status-code=TOO_MANY_REQUESTS

spring.cloud.gateway.server.webflux.routes[1].filters[2].name=CircuitBreaker
spring.cloud.gateway.server.webflux.routes[1].filters[2].args.name=userCircuit
spring.cloud.gateway.server.webflux.routes[1].filters[2].args.fallbackUri=forward:/fallback
spring.cloud.gateway.server.webflux.routes[1].filters[2].args.statusCodes=500,503
resilience4j.circuitbreaker.instances.userCircuit.failureRateThreshold=50
resilience4j.circuitbreaker.instances.userCircuit.slidingWindowSize=20
resilience4j.circuitbreaker.instances.userCircuit.minimumNumberOfCalls=10
resilience4j.circuitbreaker.instances.userCircuit.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.userCircuit.permittedNumberOfCallsInHalfOpenState=5
resilience4j.circuitbreaker.instances.userCircuit.automaticTransitionFromOpenToHalfOpenEnabled=false

#book-service
spring.cloud.gateway.server.webflux.routes[2].id=book-borrow-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://BookBorrowService
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/v1/books/**,/api/v1/categories/**,/api/v1/borrows/**

spring.cloud.gateway.server.webflux.routes[2].filters[0]=StripPrefix=2
spring.cloud.gateway.server.webflux.routes[2].filters[1].name=RequestRateLimiter
spring.cloud.gateway.server.webflux.routes[2].filters[1].args.key-resolver=#{@ipResolver}
spring.cloud.gateway.server.webflux.routes[2].filters[1].args.redis-rate-limiter.replenish-rate=2
spring.cloud.gateway.server.webflux.routes[2].filters[1].args.redis-rate-limiter.burst-capacity=10
spring.cloud.gateway.server.webflux.routes[2].filters[1].args.deny-empty-key=false
spring.cloud.gateway.server.webflux.routes[2].filters[1].args.status-code=TOO_MANY_REQUESTS
spring.cloud.gateway.server.webflux.routes[2].filters[2].name=CircuitBreaker
spring.cloud.gateway.server.webflux.routes[2].filters[2].args.name=bookCircuit
spring.cloud.gateway.server.webflux.routes[2].filters[2].args.fallbackUri=forward:/fallback
spring.cloud.gateway.server.webflux.routes[2].filters[2].args.statusCodes=500,503
resilience4j.circuitbreaker.instances.bookCircuit.failureRateThreshold=50
resilience4j.circuitbreaker.instances.bookCircuit.slidingWindowSize=20
resilience4j.circuitbreaker.instances.bookCircuit.minimumNumberOfCalls=10
resilience4j.circuitbreaker.instances.bookCircuit.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.bookCircuit.permittedNumberOfCallsInHalfOpenState=5
resilience4j.circuitbreaker.instances.bookCircuit.automaticTransitionFromOpenToHalfOpenEnabled=false

