spring.application.name=BookBorrowService
server.port=8083

eureka.client.service-url.defaultZone=http://${DISCOVERY_SERVER:localhost}:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.lease-renewal-interval-in-seconds=5
eureka.instance.lease-expiration-duration-in-seconds=10

spring.datasource.url=jdbc:postgresql://${DB_HOST_POSTGRES:localhost}:5432/book_db?reWriteBatchedInserts=true
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.password=${REDIS_PASS}
spring.data.redis.port=6379

spring.flyway.baseline-version=1
spring.flyway.baseline-on-migrate=true
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.mvc.servlet.load-on-startup=1
spring.datasource.hikari.minimum-idle=2

spring.kafka.bootstrap-servers=${BROKER_1:localhost:9092},${BROKER_2:localhost:9094},${BROKER_3:localhost:9095}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.properties.compression.type=snappy
spring.kafka.producer.properties.delivery.timeout.ms=120000
spring.kafka.producer.properties.request.timeout.ms=30000
spring.kafka.producer.properties.retry.backoff.ms=100

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.operationsSorter=alpha