syntax = "proto3";

option java_multiple_files = true;
option java_package = "com.example.grpc.user.v1";

import "google/protobuf/empty.proto";

service UserService {
  rpc getUser(GetUserRequest) returns (UserResponse);
  rpc createUser(UserCreateRequest) returns (google.protobuf.Empty);
}

message GetUserRequest {
  int64 userId = 1;
}

message UserResponse {
  int64 userId = 1;
  string email = 2;
  string fullName = 3;
}

message UserCreateRequest {
  int64 userId = 1;
  string email = 2;
  string fullName = 3;
  string phone = 4;
}
