CREATE DATABASE auth_db;
CREATE DATABASE user_db;
CREATE DATABASE book_db;
CREATE DATABASE notification_db;

CREATE USER auth_user WITH PASSWORD ${AUTH_DB_PASSWORD};
CREATE USER user_user WITH PASSWORD ${USER_DB_PASSWORD};
CREATE USER book_user WITH PASSWORD ${BOOK_DB_PASSWORD};
CREATE USER notification_user WITH PASSWORD ${NOTIFICATION_PASSWORD};

GRANT ALL PRIVILEGES ON DATABASE auth_db TO auth_user;
GRANT ALL PRIVILEGES ON DATABASE user_db TO user_user;
GRANT ALL PRIVILEGES ON DATABASE book_db TO book_user;
GRANT ALL PRIVILEGES ON DATABASE notification_db TO notification_user;